project2/Project/routes.py
from flask import Blueprint,render_template, url_for, flash, redirect, request
from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user,
    login_required,
)

main_bp = Blueprint("main", __name__)


lessons = [
    {
        "title": "Request Library Course",
        "course": "Python",
        "author": "Omar",
        "thumbnail": "thumbnail.jpg",
    },
    {
        "title": "Request Library Course",
        "course": "Python",
        "author": "Omar",
        "thumbnail": "thumbnail.jpg",
    },
    {
        "title": "Request Library Course",
        "course": "Python",
        "author": "Omar",
        "thumbnail": "thumbnail.jpg",
    },
    {
        "title": "Request Library Course",
        "course": "Python",
        "author": "Omar",
        "thumbnail": "thumbnail.jpg",
    },
    {
        "title": "Request Library Course",
        "course": "Python",
        "author": "Omar",
        "thumbnail": "thumbnail.jpg",
    },
    {
        "title": "Request Library Course",
        "course": "Python",
        "author": "Omar",
        "thumbnail": "thumbnail.jpg",
    },
]

courses = [
    {
        "name": "Python",
        "icon": "python.svg",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque quidem nihil dolor officiis at magni!",
    },
    {
        "name": "Data Analysis",
        "icon": "analysis.png",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque quidem nihil dolor officiis at magni!",
    },
    {
        "name": "Machine Learning",
        "icon": "machine-learning.png",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque quidem nihil dolor officiis at magni!",
    },
    {
        "name": "Web Design",
        "icon": "web.png",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque quidem nihil dolor officiis at magni!",
    },
    {
        "name": "Blockchain",
        "icon": "blockchain.png",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque quidem nihil dolor officiis at magni!",
    },
    {
        "name": "Tips & Tricks",
        "icon": "idea.png",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque quidem nihil dolor officiis at magni!",
    },
]

@main_bp.route("/")
@main_bp.route("/home")
def home():
    return render_template("home.html", lessons=lessons, courses=courses)


@main_bp.route("/about")

def about():
    
    return render_template("about.html", title="About")



@main_bp.route("/register", methods=["GET", "POST"])

def register():
    from app import bcrypt
    from models import db
    from forms import RegistrationForm
    from models import User
    if current_user.is_authenticated:
        return redirect(url_for("home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            fname=form.fname.data,
            lname=form.lname.data,
            username=form.username.data,
            email=form.email.data,
            password=hashed_password,
        )
        db.session.add(user)
        db.session.commit()
        flash(f"Account created successfully for {form.username.data}", "success")
        return redirect(url_for("main.login"))
    return render_template("register.html", title="Register", form=form)


@main_bp.route("/login", methods=["GET", "POST"])
def login():
    from app import bcrypt
    from forms import LoginForm
    from models import User
    if current_user.is_authenticated:
        return redirect(url_for("home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash("You have been logged in!", "success")
            return redirect(next_page) if next_page else redirect(url_for("home"))
        else:
            flash("Login Unsuccessful. Please check credentials", "danger")
    return render_template("login.html", title="Login", form=form)
@main_bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("logout"))


@main_bp.route("/dashboard")
@login_required
def dashboard():
    return render_template("dashboard.html", title="Dashboard")

project2/Project/templates/about.html
{% extends  "layout.html"%}
{%block content%}
    <h1> About page </h1>
{% endblock content  %}

project2/Project/templates/dashboard.html
{%extends "layout.html"%}
{% block content%}
<section>
    <div class="container">
        <h2>
            {{current_user.username}}
        </h2>
    </div>
</section>

project2/Project/templates/home.html
{% extends  "layout.html" %}
{%block content%}
    <h1> Home page </h1>
    {% for lesson in lessons %}
    <h2>{{ lesson.title }}</h2>
    <p> in: {{lesson.course}}</p>
    <h5>{{ lesson.author }}</h5
        >
    {% endfor %}
{% endblock content  %}

project2/Project/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>Pythonic - {{title}}</title>
    {% else %}
    <title>Pythonic</title>
    {%endif%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body class="d-flex flex-column min-vh-100">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
        <div class="container">
            <a href="/home" class="navbar-brand">Pythonic</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="/about" class="nav-link">About</a>
                        
                    </li>
                    <li class="nav-item">
                        <a href="/learn" class="nav-link">Start Learning</a>
                    </li>
                </ul>
                <!-- User Links -->
                <ul class="navbar-nav ms-auto">
                    {%if current_user.is_authenticated %}
                    <div class="dropdown show">
                        <button class="btn btn-dark bg-dark dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            My Account
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li class="nav-item">
                        <a href="/logout" class="nav-link">logout</a>
                    </li>
                    <li class="nav-item">
                        <a href="/dashboard" class="nav-link">Dashboard</a>
                    </li>
                        </ul>
                    </div>

                    
                    {%else%}
                    <li class="nav-item">
                        <a href="/register" class="nav-link">Register</a>
                    </li>
                    
                    <li class="nav-item">
                        <a href="/login" class="nav-link">Login</a>
                    </li>
                    
                    {%endif%}
                </ul>
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}} text-center">
        {{message}}
    </div>
    {% endfor %}

    {% endif %}
    {% endwith %}
    {% block content%} {% endblock %}
    <!-- footer -->

    <footer class="bg-dark mt-auto">
        <div class="container p-3">
            <div class="row text-center text-white">
                <div class="col-md-12 col-lg-4 pb-2">
                    <h4 class="text-center text-decoration-underline">Quick Links</h4>
                    <ul class=" nobull pt-3">
                        <li><a href="#" class="link text-white">Privacy Policy</a></li>
                        <li><a href="#" class="link text-white">Terms & Conditions</a></li>
                    </ul>
                </div>
                <div class="col-md-12 col-lg-4">
                    <h4 class="text-center text-decoration-underline pb-3">Social Links</h4>
                    <a href="#" class="text-white p-2"><i class="bi-github"></i></a>
                    <a href="#" class="text-white p-2"><i class="bi-youtube"></i></a>
                    <a href="#" class="text-white p-2"><i class="bi-facebook"></i></a>
                    <a href="#" class="text-white p-2"><i class="bi-twitter"></i></a>
                    <a href="#" class="text-white p-2"><i class="bi-instagram"></i></a>
                    <a href="#" class="text-white p-2"><i class="bi-tiktok"></i></a>

                </div>
                <div class="col-md-12 col-lg-4 pb-2">
                    <h4 class="text-center text-decoration-underline pb-3">Contact Us</h4>
                    <p class="lead">omar@oghoneim.com</p>
                </div>
            </div>
            <div class="col text-white text-center position-relative">
                <p class="lead font-weight-bold">Copyright &copy; 2022 | Pythonic</p>
                <a href="#" class="position-absolute bottom-0 end-0">
                    <i class="bi bi-arrow-up-circle h1"></i>
                </a>
            </div>
        </div>

    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

project2/Project/templates/login.html
{%extends "layout.html"%}
{% block content%}
<div class="container my-5 border">
    <form action="" method="POST">
        {{ form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"> Log In</legend>

            <div class="form-group">
                {{ form.email.label(class='form-control-label')}}
                {% if form.email.errors%}
                {{ form.email(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class='form-control form-control-lg')}}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.password.label(class='form-control-label')}}
                {% if form.password.errors%}
                {{ form.password(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class='form-control form-control-lg')}}
                {% endif %}

            </div>
            <div class="form-group my-3">
                {{ form.submit(class='btn btn-outline-info')}}
            </div>
            <div class="form-check">
                {{form.remember(class='form-check-input')}}
                {{form.remember.label(class='form-check-input-label')}}
            </div>
        </fieldset>
    </form>
    <small class="text-muted ml-2">
        <a href="#">Forgeot Password?
        </a>
    </small>
    <small class="text-muted">
        Need An Account?
        <a class="ml-2" href="{{url_for('main.register')}}"> Sign Up Here</a>
    </small>
</div>
{% endblock content %}

project2/Project/templates/register.html
{%extends "layout.html"%}
{% block content%}
<div class="container mt-auto align-items-center">
    <form action="" method="POST">
        {{ form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"> Create an Account</legend>
            <div class="form-group">
                {{ form.fname.label(class='form-control-label')}}
                {% if form.fname.errors%}
                {{ form.fname(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">
                    {% for error in form.fname.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.fname(class='form-control form-control-lg')}}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.lname.label(class='form-control-label')}}
                {% if form.lname.errors%}
                {{ form.lname(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">
                    {% for error in form.lname.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.lname(class='form-control form-control-lg')}}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.username.label(class='form-control-label')}}
                {% if form.username.errors%}
                {{ form.username(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class='form-control form-control-lg')}}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.email.label(class='form-control-label')}}
                {% if form.email.errors%}
                {{ form.email(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class='form-control form-control-lg')}}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.password.label(class='form-control-label')}}
                {% if form.password.errors%}
                {{ form.password(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class='form-control form-control-lg')}}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class='form-control-label')}}
                {% if form.confirm_password.errors%}
                {{ form.confirm_password(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class='form-control form-control-lg')}}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info')}}
            </div>
        </fieldset>
    </form>
    <div class="broder-top pt-3">
        <small class="text-muted">
            Already have an Account?
            <a href="{{url_for('main.login')}}" class="ml-2">Sign in</a>
        </small>
    </div>
</div>
{% endblock content %}